# Generated by Django 4.0.2 on 2022-02-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='discription',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
